rottenwood_booking_pages:
    resource: "@RottenwoodBookingBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /

rottenwood_booking:
    resource: "@RottenwoodBookingBundle/Controller/RestController.php"
    type:     annotation
    prefix:   /rest
